### ISSUE TITLE
HOLOCHAIN_WEBSOCKET_DISCONNECTED

### ISSUE THREAD

**Issue by kristoferlund** [holochain/hc-redux-middleware#3]
https://github.com/holochain/hc-redux-middleware/blob/a1796cefa799ad9179e98dbad7f2e0b6b689d948/src/lib/middleware.ts#L14

Suggestion - Let the middleware dispatch an action when connection is dropped as well. 

 `HOLOCHAIN_WEBSOCKET_DISCONNECTED`

Let me know and I'll make a PR.

**Comment by Connoropolous** [comment]
Sounds like a good idea!

**Comment by willemolding** [comment]
Yes I would really like to see this implemented! In fact it is almost a requirement for robust and reactive UIs. 

I'm not sure what the implementation would look like at this stage since all the middleware does is manage promises from hc-web-client. I would be interested to hear some ideas

**Comment by kristoferlund** [comment]
hc-web-client would need to subscribe to `event:close` from rpc-websocket. 

https://github.com/elpheria/rpc-websockets/blob/HEAD/API.md#event-close

```
ws.subscribe('close')
ws.on('close', handlerFunction)
```

**Comment by willemolding** [comment]
Oooh and I just remembered that the `ws` is returned by the connect promise. This could actually be really easy
